version: '2'

services:
  virtuoso:
    image: tenforce/virtuoso:1.3.1-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DBA_PASSWORD: "mysecret"
    volumes:
      - ./data/virtuoso:/data
    ports:
      - "1111:1111"
      - "8890:8890"

  kabara:
    image: registry.diginfra.net/tsd/kabara:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      TRIPLE_STORE_URL: "http://virtuoso:8890"
      TRIPLE_STORE_SPARQL_PATH: "/sparql-auth"
      DATA_PATH: ./data
      PUBLIC_URL: http://localhost:9000
