version: '2'

services:
  blazegraph:
    image: ontotext/graphdb:10.0.2
    environment:
      GDB_JAVA_OPTS: "-Dgraphdb.home=/opt/graphdb/home"
    volumes:
      - ./data/graphdb:/opt/graphdb/home
    ports:
      - "7200:7200"

  kabara:
    image: registry.diginfra.net/tsd/kabara:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      TRIPLE_STORE_URL: "http://graphdb:7200"
      TRIPLE_STORE_SPARQL_PATH: "/repositories/{name}"
      TRIPLE_STORE_SPARQL_WRITE_PATH: "/repositories/{name}/statements"
      DATA_PATH: ./data
      PUBLIC_URL: http://localhost:9000
