version: '2.1'
services:
  my_virtdb:
    image: tenforce/virtuoso:1.3.1-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DBA_PASSWORD: "mysecret"
    volumes:
      - ./data/virtuoso:/data
    ports:
      - "1111:1111"
      - "8890:8890"
  kabara:
    image: kabara:local
    ports:
      - "9000:9000"
      - "9001:9001"
